name: Docker build container

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  docker-build-container:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker system prune -af

      - name: Get repository name
        id: repo-basename
        run: |
          echo "repo=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build docker image
        uses: senzing-factory/github-action-docker-buildx-build@v2
        with:
          image-repository: senzing/${{ steps.repo-basename.outputs.repo }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
