name: Go test linux - oracle

on: [push]

env:
  SENZING_LOG_LEVEL: TRACE
  SENZING_TOOLS_DATABASE_URL: "oci://sys:Passw0rd@oracle:1521/G2"

permissions:
  contents: read

jobs:
  go-test-linux:
    name: "Go test with Senzing: ${{ matrix.senzingsdk-version }}; OS: ${{ matrix.os }}; Go: ${{ matrix.go }} - oracle"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]
        senzingsdk-version: [staging-v4]

    services:
      oracle:
        # https://container-registry.oracle.com/ords/ocr/ba/database/free
        env:
          ORACLE_PWD: Passw0rd
        image: container-registry.oracle.com/database/free
        ports:
          - 1521:1521

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy rootfs files
        run: sudo cp --verbose --recursive rootfs/* /

      - name: Copy testdata files
        run: sudo cp --verbose --recursive testdata/oracle/rootfs* /

      - name: Install Senzing SDK
        uses: senzing-factory/github-action-install-senzing-sdk@v3
        with:
          packages-to-install: "senzingsdk-runtime senzingsdk-setup"
          senzingsdk-repository-package: ${{ secrets.SENZING_APT_BETA_STAGING_REPOSITORY_PACKAGE }}
          senzingsdk-repository-path: ${{ secrets.SENZING_APT_BETA_STAGING_REPOSITORY_URL }}

      - name: Install dependencies
        run: |
          curl --output /tmp/instantclient-basic-linux.zip https://download.oracle.com/otn_software/linux/instantclient/2350000/instantclient-basic-linux.x64-23.5.0.24.07.zip
          sudo mkdir -p /opt/oracle
          sudo unzip -d /opt/oracle /tmp/instantclient-basic-linux.zip
          sudo apt-get install libaio1t64 libaio-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/libaio.so.1

      - name: Paths - 1
        run: |
          ls /opt

      - name: Paths - 2
        run: |
          ls /opt/oracle

      - name: Paths - 3
        run: |
          ls /opt/oracle/instantclient_23_5

      - name: Paths - 4
        run: |
          ls /opt/oracle/instantclient_23_5/network

      - name: Paths - 5
        run: |
          ls /opt/oracle/instantclient_23_5/network/admin

      - name: Paths - 5
        run: |
          cat /opt/oracle/instantclient_23_5/network/admin/tnsnames.ora

      - name: Run go test
        run: |
          export SENZING_PATH="/opt/senzing"
          export LD_LIBRARY_PATH="${SENZING_PATH}/er/lib:/opt/oracle/instantclient_23_5"
          go test -json -v -p 1 ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
